### ISSUE TITLE
Automatic workers on hybrid CPUs

### ISSUE THREAD

**Issue by ooferdww** [porcino/Av1ador#1]
It completely breaks on hybrid CPUs (my i5-13600KF for example) and keeps adding workers until it crashes.

**Comment by porcino** [comment]
Just to be sure, did you by any chance use a gpu accelerated filter? I also need to measure the gpu usage. Anyway I added a limit for now (amount of cpu cores)

**Comment by ooferdww** [comment]
> 

didnt use any filters, just aom encoding with every setting as default

**Comment by ooferdww** [comment]
this issue still occurs on the current nightly

**Comment by porcino** [comment]
A workers limit have been added in 1219bb041b5e5f0b442aee137164224bd91ec26a
