### ISSUE TITLE
[Feature Request] Two-pass encoding.

### ISSUE THREAD

**Issue by Artoch47** [porcino/Av1ador#11]
Please add two-pass encoding option for the codecs that support it.
The first pass can take a while to finish, but the smaller file size and better detail are worth it.

There is an example of two-pass encode using libaom-av1 here:
https://trac.ffmpeg.org/wiki/Encode/AV1

**Comment by porcino** [comment]
I tried 2 pass before, but the gain (like 0.01% in score) vs the speed lost by filtering twice (tonemapping, denoising, etc) is not worth. Also ffmpeg doesn't report the time progress on the first pass for whatever reason, so the progress bar is going to be more innacurate

**Comment by Artoch47** [comment]
Still, having it as an optional feature would be nice. I don't mind waiting if it means a smaller file size.
The VP9 could also benefit from it, more than the AV1.

**Comment by porcino** [comment]
> The VP9 could also benefit from it, more than the AV1.

You are right, VP9 benefit from it, so now VP9 will always use 2pass when auto-alf-ref is enabled 151438bf4af2f764e20e61ca9ab6616ff3118962
