### ISSUE TITLE
Queue file corrupted on power loss

### ISSUE THREAD

**Issue by Anacondo** [porcino/Av1ador#22]
Hello,

The other day the electricity went off in the middle of an encode and when I rebooted my PC the queue file was corrupted, full of unreadable characters. I had 10 files in the queue, each with specific settings like cropping, filters, CRF values, etc. so it was quite a pain to redo all that. Would it be possible to prevent this somehow?

Best regards!

**Comment by porcino** [comment]
This would be impossible for me to test, but in the commit 6496923 the queue.xml will be renamed to queue.xml.bak before saving the queue

**Comment by Anacondo** [comment]
Many thanks! I hope I won't need it, but if it crashes again I will let you know how it went.
