### ISSUE TITLE
crash on queuing file (version 1.0.11)

### ISSUE THREAD

**Issue by chocobeau** [porcino/Av1ador#4]
[log_2023-07-31_11-16-38.txt](https://github.com/porcino/Av1ador/files/12213488/log_2023-07-31_11-16-38.txt)

**Comment by porcino** [comment]
Can you try with the latest version? https://github.com/porcino/Av1ador/releases/tag/Nightly

**Comment by chocobeau** [comment]
Sure, it still crash 
[log_2023-07-31_22-55-36.txt](https://github.com/porcino/Av1ador/files/12222201/log_2023-07-31_22-55-36.txt)

**Comment by porcino** [comment]
Sorry, one more time please? https://github.com/porcino/Av1ador/releases/download/Nightly/Av1ador-nightly.zip

**Comment by chocobeau** [comment]
NP, sorry to bother you , perhaps it's my system (i don't know, i'm not a dev)
[log_2023-07-31_23-22-35.txt](https://github.com/porcino/Av1ador/files/12222386/log_2023-07-31_23-22-35.txt)

**Comment by porcino** [comment]
Ok this is weird, is the browser downloading the zip archive again and not using the cache right?

**Comment by chocobeau** [comment]
the archive hash give this :  Nom: Av1ador-nightly.zip
Taille: 60802916 octets (57 MiB)
CRC32: 32D34411
CRC64: BAE694C911A31683
SHA256: 4adef60d91b728806381a79cb4eaa7be8833f59f409eab6069839eb9679be70b
SHA1: a8ebffe1576b7303c02c2c29212a56bafd6273b2
BLAKE2sp: f23ea43e841681b7a6777d5131691947a5277aff8b88f48e75fab0f819d65192
[log_2023-07-31_23-36-07.txt](https://github.com/porcino/Av1ador/files/12222460/log_2023-07-31_23-36-07.txt)

**Comment by porcino** [comment]
I'd need the info of the video. Can you move the video and this batch file where Av1ador.exe is, and run it?
[duration.zip](https://github.com/porcino/Av1ador/files/12222579/duration.zip)
I'd need the output file "output.txt"

**Comment by chocobeau** [comment]
Here we go : 
[output.txt](https://github.com/porcino/Av1ador/files/12225086/output.txt)

**Comment by porcino** [comment]
Ok, I found out that the parsing of doubles is different based on the regional formatting, I made a change to make it invariant, give it another try...

**Comment by chocobeau** [comment]
Thank you, the issue is resolved :)
