### ISSUE TITLE
Feature request: Subtitle burn in

### ISSUE THREAD

**Issue by jkkma** [porcino/Av1ador#5]
There are some situations where subtitle burn-in is needed like with .ass subtitles that have special positioning and don't work if you upload them to sites where it isn't supported.

**Comment by porcino** [comment]
Ok, if you add the filter "subtitles", it's already possible, anyway I just added a menu entry to make it easier to input the path.
If you want to override the subtitle style check the documentation here [https://ffmpeg.org/ffmpeg-filters.html#subtitles](url)

**Comment by jkkma** [comment]
im getting this error trying to burn in .ass subs 
![Screenshot 2023-08-05 204439](https://github.com/porcino/Av1ador/assets/16640398/be7983e9-9d2e-4d1f-bad1-d34b79d52ef7)
Is the ffmpeg in av1ador compiled with --enable-libass like it says in the ffmpeg documentation?
https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo#subtitlesfilter
or is this a different error?

**Comment by jkkma** [comment]
I think it was an issue with the file path, some characters not correctly escaped so now i put the video in a simple path and added this custom filter: "subtitles='C\:\\Users\\ayybased\\Videos\\coolvideo.mkv'" and it works. There was also a backslash missing before the : character which was an issue too. Also for ease of use instead of going through extra step of extracting sub files you can just set the "subtitles=" parameter to the video path, libass will automatically pick the sub file out of it.
![Screenshot 2023-08-05 210652](https://github.com/porcino/Av1ador/assets/16640398/a946d556-1b12-4338-a6d5-6c503b83f748)

**Comment by porcino** [comment]
Oh awesome you found the issue, updating it, thanks!
