### ISSUE TITLE
Av1ador failure on video concatenation.

### ISSUE THREAD

**Issue by jkkma** [porcino/Av1ador#6]
Hello I don't know how this could be reproducible, but im having issues encoding a near one hour video to av1 using svt. When the encoding finishes the .ivf files just sit in av1adors temp folder and no file is generated in the output folder. When i hit to encode again and it asks me to resume previous encode it encodes super fast but leads to same result, no output.
![Screenshot 2023-08-10 191048](https://github.com/porcino/Av1ador/assets/16640398/5801e963-1478-402d-aabb-336ec50298c5)
![Screenshot 2023-08-10 191548](https://github.com/porcino/Av1ador/assets/16640398/42827540-904e-4b96-b282-67ea35c20f7c)
![Screenshot 2023-08-10 191656](https://github.com/porcino/Av1ador/assets/16640398/b1d08783-f02d-4968-9cbf-12c017d11cc4)

**Comment by porcino** [comment]
I can't reproduce this issue, I encoded a video with the exact same settings and worked, does it have write permission on the output folder? maybe try changing the output folder

**Comment by porcino** [comment]
Thanks for reporting, for some reason ffmpeg concat doesn't allow the number symbol in the input path "#", I use just the temp folder now, check if it works.
